### ISSUE TITLE
Different currency dropdown

### ISSUE THREAD

**Issue by kevin-webdev** [WixEdit/WixEdit#16]
My issue is that I have Amazon  associate account and which is from India and have all the products which is associate link in India the problem is if anybody wants to buy but are from   Us or UK and but when they click on my link it's  shows the Indian currency only  so how do I change it so that ppl using Amazon in different countries and buy products  ..

**Comment by icnocop** [comment]
Hi @kevin-webdev I don't think your question is relevant to WixEdit.

This project is not related to wix.com, the website builder.

Thank you.
