### ISSUE TITLE
Wrong namespace

### ISSUE THREAD

**Issue by pierrejochem** [WixEdit/WixEdit#2]
Is there a way to correct his:

![grafik](https://user-images.githubusercontent.com/9192953/36471085-80ecccfa-16ed-11e8-87d5-b97420f93614.png)

I changed the settings linke this, but without success:

![grafik](https://user-images.githubusercontent.com/9192953/36471182-d4c72636-16ed-11e8-9d8d-8f72b0f622a5.png)

**Comment by icnocop** [comment]
It seems your "WiX Binaries Directory" field has a value of "...".

I expected it to be set to "C:\Program Files (x86)\WiX Toolset v4.0\bin"

**Comment by pierrejochem** [comment]
Thank you :-)
