### ISSUE TITLE
Can't change size of dialog

### ISSUE THREAD

**Issue by jcoryatjr** [WixEdit/WixEdit#24]
Trying to change the dialog from the initial size gives an error "Value is not in the valid range of numbers."  What?  You can't change the size of the dialog at all?

**Comment by russrayner** [comment]
Just ran across this as well - changing it in the file worked fine.  So far UI does not through an error after saving new size.

**Comment by icnocop** [comment]
This has been fixed in [v0.8.628.2](https://github.com/WixEdit/WixEdit/releases/tag/v0.8.628.2)
