### ISSUE TITLE
error CNDL0010 : The Control/@Property attribute was not found; it is required when attribute CheckBoxPropertyRef is specified.

### ISSUE THREAD

**Issue by jholovacs** [WixEdit/WixEdit#3]
Creating a checkbox apparently needs to be bound to a property, but that is not available in the UI.

**Comment by icnocop** [comment]
1. Right-click in the white-space in the properties area when the checkbox control is selected.
2. Select New
3. Select Property
4. Click Ok

Let me know if that doesn't work for you.

Thank you.
