### ISSUE TITLE
noob tries wixedit

### ISSUE THREAD

**Issue by LogSpider** [WixEdit/WixEdit#40]
So far i did:

- .NET SDK 6 download and install
- `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org`
- `dotnet tool install --global wix`
- starting wixedit
- adding `C:\Users\my.user\.dotnet\tools\` over tools > options > wix bin dir
- getting error that wix.xsd is missing

![image](https://github.com/WixEdit/WixEdit/assets/96056194/765cfa58-9c9f-4004-ae16-c83c5b29a87e)

im very sorry, im completly new to wixedit

**Comment by Overwatch-C-17** [comment]
I'm pretty sure the program is looking for the documentation file to show the description of each wix elements on WixEdit to help you during the creation of the MSI package.

Have you ever try Wix 3.11 or 3.14 (Beta)? 
Wix 3.11 and 3.14 (Beta) still works great for authoring MSI package with Wixedit

**Comment by icnocop** [comment]
Hi @LogSpider 

Thank you for trying to use WixEdit and for leaving your feedback.

Thank you @Overwatch-C-17 for sharing your knowledge as well.

I've updated WixEdit to support basic Wix v4 wxs files.
For example:
1. Run `dotnet tool install --global wix --version 4.0.2` to download and install the WiX 4.0.2 tools.
The process may work for other versions of WiX too.
2. Tools > Options > WiX Binaries Directory > `%userprofile%\.dotnet\tools\.store\wix\4.0.2\wix\4.0.2`
3. Load a Wix 4 wxs file using File > Open.
4. Build > Build MSI setup package

The changes are still pending a code review from @jkeuper .

In the meantime, you can try out the new version of WixEdit from the download links on the bottom of this page: 
https://github.com/WixEdit/WixEdit/actions/runs/6451229990

Thank you.

**Comment by Floyddotnet** [comment]
artefacts are expired. can you pls reupload them?

**Comment by icnocop** [comment]
@Floyddotnet thank you for bringing this to my attention.

An update to WixEdit was published with these changes:
https://github.com/WixEdit/WixEdit/releases/tag/v0.8.2712.17

Thank you.
