### ISSUE TITLE
"Help > WiX Tutorial" redirects from http://www.tramontana.co.hu/wix/ to https://www.firegiant.com/wix

### ISSUE THREAD

**Issue by icnocop** [WixEdit/WixEdit#7]
"Help > WiX Tutorial" redirects from http://www.tramontana.co.hu/wix/ to https://www.firegiant.com/wix

I'm not sure if the tutorials that were on tramontana.co.hu are still relevant, if we want to reference archived versions of the tutorials that were on tramontana.co.hu , or if there are equivalent tutorials on firegiant.com, etc.

**Comment by jkeuper** [comment]
The original tutorials are moved to the following location:
https://www.firegiant.com/wix/tutorial/

Op di 6 aug. 2019 01:52 schreef Rami <notifications@github.com>:
